// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDUrt4JFjvPBqFMVG32CNMZO6JuN20mUs',
    appId: '1:772379802860:web:f2168d84ed4a29f16279c9',
    messagingSenderId: '772379802860',
    projectId: 'agrivest-866ab',
    authDomain: 'agrivest-866ab.firebaseapp.com',
    storageBucket: 'agrivest-866ab.appspot.com',
    measurementId: 'G-WDSBFSTHWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMHb2IbKA1YKbMiPKgWqjGNM12c0B7tQ',
    appId: '1:772379802860:android:897bf88358843e3c6279c9',
    messagingSenderId: '772379802860',
    projectId: 'agrivest-866ab',
    storageBucket: 'agrivest-866ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Ug9H-KJwlNKpE48Rh9KrEH2_mcK6PrA',
    appId: '1:772379802860:ios:6b0919ac36ab816b6279c9',
    messagingSenderId: '772379802860',
    projectId: 'agrivest-866ab',
    storageBucket: 'agrivest-866ab.appspot.com',
    iosClientId: '772379802860-jkejau5mfh0am0aqa077mkcdslsjgafi.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdgHackatonApp',
  );
}
